### ISSUE TITLE
Models not showing since VSCode 2020 June update

### ISSUE THREAD

**Issue by Degubi** [stef-levesque/vscode-3dviewer#11]
**Bug description:** Models not showing up, only an empty scene is displayed (both in 'Viewer' and 'Editor' modes)
**Steps to reproduce:** Update to VSCode 2020 June (v1_47)
The format of the model on the images is 'obj'

**Using 'v1_46'** (May update)
![may](https://user-images.githubusercontent.com/13366932/88029787-bbf29380-cb3a-11ea-9912-3dfd86b90d7c.png)

**Using 'v1_47'** (June update)
![june](https://user-images.githubusercontent.com/13366932/88029885-d7f63500-cb3a-11ea-8c1d-f73483f69b7b.png)

**Comment by kangxue** [comment]
> VSCode 2020 J

I have the same issue

**Comment by Josverl** [comment]
samesame , 
are you using native binding? then the upgrade probably caused your bindings to mismatch

**Comment by Degubi** [comment]
So looking for issues I found this error that may be related to this issue:
webviewElement.ts:160 [Embedded Page] Access to XMLHttpRequest at 'vscode-resource:/c%3A/Users/User/Desktop/modelFolder/model.obj' from origin 'vscode-webview://29619235-bf9d-499e-875a-29ec83297b0d' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, vscode-webview-resource, data, chrome, vscode-webview, https.

**Comment by Degubi** [comment]
Made some changes regarding path handling, see #12
Someone should test this, it was working for me locally
