### ISSUE TITLE
HELP: How to open this modelviewer?

### ISSUE THREAD

**Issue by hopepdm** [stef-levesque/vscode-3dviewer#15]
which shortcut key wake up window?

**Comment by Degubi** [comment]
- You click on a model file in your project
- A popup comes up where you click 3D Mesh Viewer

![Képernyőkép 2020-09-16 191400](https://user-images.githubusercontent.com/13366932/93370335-f33aa380-f850-11ea-8c6e-18a20d3dffe4.png)

**Comment by hopepdm** [comment]
@Degubi tks

**Comment by jpryne** [comment]
I'm unable to open the viewer or editor. Running headmelted (VSCode) under Ubuntu-MATE on a Raspberry Pi 4.

**Comment by stef-levesque** [comment]
This extension use THREE.js and require a WebGL-compatible platform to render the meshes. It is likely not supported on RPi 4

**Comment by jjant** [comment]
add this info in the readme please, also please add a command for it (so you can open it from cmd+p)

**Comment by Degubi** [comment]
Hi @jjant!
I created a pr for fixing the docs issues & adding the commands. #29

![image](https://user-images.githubusercontent.com/13366932/150688251-779061df-96cb-4d09-922e-6870d6fa2da3.png)

When using these commands a file browser pops up (like when using the File: Open file... command).
After selecting a model file it opens up in the viewer/editor.

**Comment by jjant** [comment]
@Degubi Thanks, that's really useful!

**Comment by RokeJulianLockhart** [comment]
![image](https://github.com/stef-levesque/vscode-3dviewer/assets/42837531/3a72438e-c78c-4dbc-94dc-57a67c9458b6)

Am I doing something incorrectly? This is a powerful desktop system running the newest version of KDE on OpenSUSE Tumbleweed.

**Comment by Degubi** [comment]
Hi @rokejulianlockhart 
Unfortunately the commands aren't yet active on the currently published version... :/
See #29
