### ISSUE TITLE
no "Open Mesh Preview" option

### ISSUE THREAD

**Issue by hyc0612** [stef-levesque/vscode-3dviewer#3]

**Comment by stef-levesque** [comment]
Sorry, not sure I understand what you mean. Where would you want to see this option ?

**Comment by hyc0612** [comment]
i want to preview a .obj file with vscode-3dviewer and cant find a way to
preview it

stef-levesque <notifications@github.com> 于2018年10月5日周五 上午2:50写道：

**Comment by stef-levesque** [comment]
In VSCode, open the folder where the .obj is located 

Then in the Explorer section, right-click on the .obj file, and select ´Open In Viewer’

Do you see a new tab opening ?

**Comment by hyc0612** [comment]
Thank you and problem solved. The reason why I couldn't find the "Open In
Viewer" is because I did not "open a folder".

stef-levesque <notifications@github.com> 于2018年10月7日周日 下午9:52写道：
