### ISSUE TITLE
how to open disk file?

### ISSUE THREAD

**Issue by beantowel** [stef-levesque/vscode-3dviewer#4]

**Comment by stef-levesque** [comment]
In the Explorer section of the Editor, you should see the option to “Open in Viewer” when right-clicking on a compatible file format.

Otherwise, you can use the command palette “Open URL in Viewer” and copy the file path, using the “file://“ prefix.

**Comment by stef-levesque** [comment]
Try to open the folder containing the file, and right-click on it in the Explorer section, not the Open Editor section.

**Comment by stef-levesque** [comment]
Alternatively, you can use the command palette to run `openUrlInViewer` and specify your local file with the `file:///` scheme. 
(E.g. file:///Users/me/Documents/file.stl )

**Comment by rawnsley** [comment]
@stef-levesque Thanks - it works outside of the Open Editor section. Strange behaviour, but that's on Code not you.
